DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                    app VARCHAR(55) NOT NULL,
                                    uri VARCHAR(255) NOT NULL,
                                    ip VARCHAR(55) NOT NULL,
                                    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                                    CONSTRAINT pk_hit PRIMARY KEY (id)
);