version: '3.1'
services:
  stats-server:
    build: stats/service
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=12345
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    container_name: stats_db_container
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=12345

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
